//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarMax.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LinesAndCaptions")]
        public global::SolarMax.ConstellationMode ConstellationMode {
            get {
                return ((global::SolarMax.ConstellationMode)(this["ConstellationMode"]));
            }
            set {
                this["ConstellationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cylindrical")]
        public global::SolarMax.ProjectionMode ProjectionMode {
            get {
                return ((global::SolarMax.ProjectionMode)(this["ProjectionMode"]));
            }
            set {
                this["ProjectionMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowEclipticGrid {
            get {
                return ((bool)(this["ShowEclipticGrid"]));
            }
            set {
                this["ShowEclipticGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEquatorialGrid {
            get {
                return ((bool)(this["ShowEquatorialGrid"]));
            }
            set {
                this["ShowEquatorialGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLocalGrid {
            get {
                return ((bool)(this["ShowLocalGrid"]));
            }
            set {
                this["ShowLocalGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ecliptic")]
        public global::SolarMax.ViewMode ViewMode {
            get {
                return ((global::SolarMax.ViewMode)(this["ViewMode"]));
            }
            set {
                this["ViewMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowInstruments {
            get {
                return ((bool)(this["ShowInstruments"]));
            }
            set {
                this["ShowInstruments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelp {
            get {
                return ((bool)(this["ShowHelp"]));
            }
            set {
                this["ShowHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public global::SolarMax.CaptionMode CaptionMode {
            get {
                return ((global::SolarMax.CaptionMode)(this["CaptionMode"]));
            }
            set {
                this["CaptionMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowData {
            get {
                return ((bool)(this["ShowData"]));
            }
            set {
                this["ShowData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float MinStarBrightness {
            get {
                return ((float)(this["MinStarBrightness"]));
            }
            set {
                this["MinStarBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2.1377762305788766")]
        public double SurfaceLongitude {
            get {
                return ((double)(this["SurfaceLongitude"]));
            }
            set {
                this["SurfaceLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65663164969475551")]
        public double SurfaceLatitude {
            get {
                return ((double)(this["SurfaceLatitude"]));
            }
            set {
                this["SurfaceLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAltConstellationShapes {
            get {
                return ((bool)(this["UseAltConstellationShapes"]));
            }
            set {
                this["UseAltConstellationShapes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WireFrameBodyRender {
            get {
                return ((bool)(this["WireFrameBodyRender"]));
            }
            set {
                this["WireFrameBodyRender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayTimeUTC {
            get {
                return ((bool)(this["DisplayTimeUTC"]));
            }
            set {
                this["DisplayTimeUTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HighQualityRender {
            get {
                return ((bool)(this["HighQualityRender"]));
            }
            set {
                this["HighQualityRender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Moon")]
        public string DefaultViewTarget {
            get {
                return ((string)(this["DefaultViewTarget"]));
            }
            set {
                this["DefaultViewTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle ScreenBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["ScreenBounds"]));
            }
            set {
                this["ScreenBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HighlightSunlitAreas {
            get {
                return ((bool)(this["HighlightSunlitAreas"]));
            }
            set {
                this["HighlightSunlitAreas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowConstellationBoundaries {
            get {
                return ((bool)(this["ShowConstellationBoundaries"]));
            }
            set {
                this["ShowConstellationBoundaries"] = value;
            }
        }
    }
}
